"""cascade_delete_transactions

Revision ID: 4f261b1b9e44
Revises: 96ac5a1dabea
Create Date: 2026-06-13 14:38:12.266448

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f261b1b9e44'
down_revision = '96ac5a1dabea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_card_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'cards', ['card_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_card_id_fkey', 'transactions', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###
